### ISSUE TITLE
Page that embeds video for lecture as well as description about lecture

### ISSUE THREAD

**Issue by erickjperez** [usd-cs/comp495-sp18-flipped-tech#10]
This page should be a template page that will be taking a respective video link and description of the lecture and is able to output it onto the page. Must be able to take different links and descriptions and output it on the page

**Comment by SatGarcia** [comment]
How does this relate to #11? Seems to be the same thing.

**Comment by erickjperez** [comment]
sorry about the lack of clarity, but this issue handles only the webpage and the content on it. For this issue, the assignee must be able to embed the video on the page. Issue #11 is about sending the video, its title, description, and course to this page for Jack to work on. I will update both this issue and issue #11 to reflect that
