### ISSUE TITLE
Send Comments From Lecture Comment Section Back To Database

### ISSUE THREAD

**Issue by erickjperez** [usd-cs/comp495-sp18-flipped-tech#13]
Whenever a new comment is added to the comments under a given lecture, add it to the comment section and send that back to the database so that the comments can persist and be able to look back on them in the future

**Comment by wcarhart** [comment]
@erickjperez yo how's the progress on this?

**Comment by erickjperez** [comment]
@wcarhart we're getting pretty close. We are able to successfully load the comments and also write comments to the DB. The only problem we have now is syncing the state with the database in real time. We're hoping to get it finished tonight #TheGrindNeverStops

**Comment by wcarhart** [comment]
@erickjperez good to hear. I will observe with great anticipation

**Comment by erickjperez** [comment]
@wcarhart thank you William H. Carhart. I will observe with great anticipation you observing us with great anticipation
