### ISSUE TITLE
Store Video and Information About Lecture in Database

### ISSUE THREAD

**Issue by erickjperez** [usd-cs/comp495-sp18-flipped-tech#15]
After a professor uploads the information in the video upload page, this data must then be taken and stored in the database that can be easily stored and retrieved. The data to be stored includes the course, the title of the lecture, the lecture video link, and a description of the lecture. This issue is solely a database task

**Comment by SatGarcia** [comment]
This is too ambiguous. What is "relevant info." This should be specified before hand so the reviewer can know whether it is correct or not. Also, is this simply a database task or also updating the webpage to send data to the database?

**Comment by erickjperez** [comment]
This is only a database task. I will update the description above with this info as well as what "relevant info" means
