### ISSUE TITLE
Store Comments In Database

### ISSUE THREAD

**Issue by erickjperez** [usd-cs/comp495-sp18-flipped-tech#16]
For the comment section under the lectures, they must be stored in the database in order for the data to persist and can be looked back on in the future. It should be stored efficiently and be able to passed back to the respective lecture to be output on the page

**Comment by SatGarcia** [comment]
This task is a little ambiguous. Is this simply updating the database to accept comments, or does it include updating both the webpage and the database to make everything work together to store the comments?

**Comment by erickjperez** [comment]
We were a little unsure about what setting up a database entails. Seth was going to look more into it this weekend and get back to me with specifics about what can be done and how long it will take. My apologies for the ambiguity, but we saw this issue mainly as storing/updating the only database, not the webpage.
